Repository AY2324S1-CS2113T-W11-1/tp, pull requests merged in 2023-10, with the labels that each got.

#22 Add UI Class
  src/main/java/seedu/commands/Command.java
  src/main/java/seedu/commands/DeleteCommand.java
  src/main/java/seedu/commands/FindCommand.java
  src/main/java/seedu/commands/HelpCommand.java
  src/main/java/seedu/commands/ListCommand.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/ui/UI.java
  src/test/java/seedu/DukeTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High

#25 Add Resource class
  src/main/java/data/Book.java
  src/main/java/data/Resource.java
  src/main/java/seedu/commands/AddCommand.java
  src/main/java/seedu/commands/ListCommand.java
  src/main/java/seedu/parser/Parser.java
Labels: priority.High

#29 Update ListCommand and edit Resource and Book
  docs/AboutUs.md
  docs/team/pictures/yingxia_portfolio.jpg
  src/main/java/data/Book.java
  src/main/java/data/Resource.java
  src/main/java/seedu/commands/ListCommand.java
Labels: priority.High

#27 Add HelpCommand
  src/main/java/seedu/commands/HelpCommand.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/ui/UI.java
Labels: priority.High

#28 Add ExitCommand
  src/main/java/seedu/commands/ExitCommand.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/ui/UI.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#30 Change syntax to "exit" and updated test
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/parser/Parser.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Bug

#31 Update AddCommand.java and Add SysLibException.java
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/JoanneAng.md
  docs/team/pictures/joanneang_portfolio.jpg
  src/main/java/data/Book.java
  src/main/java/data/SysLibException.java
  src/main/java/seedu/commands/AddCommand.java
  src/main/java/seedu/commands/Command.java
  src/main/java/seedu/commands/DeleteCommand.java
  src/main/java/seedu/commands/ListCommand.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/ui/UI.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High

#32 Add FindCommand class
  src/main/java/seedu/commands/AddCommand.java
  src/main/java/seedu/commands/Command.java
  src/main/java/seedu/commands/FindCommand.java
  src/main/java/seedu/data/Book.java
  src/main/java/seedu/data/Resource.java
  src/main/java/seedu/data/SysLibException.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/ui/UI.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Story, priority.High

#33 Add Tag Function
  docs/UserGuide.md
  src/main/java/seedu/commands/AddCommand.java
  src/main/java/seedu/commands/Command.java
  src/main/java/seedu/data/Book.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/ui/UI.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Story, priority.High

#34 Update Listing by specific filters for ListCommand.Java
  src/main/java/seedu/commands/ListCommand.java
  src/main/java/seedu/parser/Parser.java
Labels: type.Enhancement

#39 Update UserGuide.md for List and minor change to ListCommand
  docs/UserGuide.md
  src/main/java/seedu/commands/ListCommand.java
Labels: type.Enhancement

#38 Add Junit
  src/main/java/seedu/parser/Parser.java
  src/test/java/seedu/commands/ExitCommandTest.java
  src/test/java/seedu/commands/HelpCommandTest.java
  src/test/java/seedu/parser/DeleteParserTest.java
  src/test/java/seedu/parser/ParserTest.java
  src/test/java/seedu/util/TestUtil.java
Labels: priority.High

#41 Add jUnit tests for ListCommand
  src/test/java/seedu/commands/ListCommandTest.java
  src/test/java/seedu/util/TestUtil.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Enhancement

#42 Fix consistency
  src/main/java/seedu/commands/AddCommand.java
  src/main/java/seedu/commands/DeleteCommand.java
  src/main/java/seedu/commands/FindCommand.java
  src/main/java/seedu/commands/ListCommand.java
  src/main/java/seedu/data/Book.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/ui/UI.java
  src/test/java/seedu/commands/HelpCommandTest.java
  src/test/java/seedu/commands/ListCommandTest.java
  src/test/java/seedu/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement

#44 Fix HelpCommand
  docs/UserGuide.md
  src/main/java/seedu/ui/UI.java
  src/test/java/seedu/commands/HelpCommandTest.java
  src/test/java/seedu/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, type.Bug

#45 Fix bug where listing by genre crashes SysLib
  src/main/java/seedu/commands/ListCommand.java
  src/test/java/seedu/util/TestUtil.java
Labels: type.Bug

#49 Add Junit tests for FindCommand
  src/main/java/seedu/commands/FindCommand.java
  src/test/java/seedu/commands/FindCommandTest.java
  src/test/java/seedu/parser/ParserTest.java
Labels: type.Enhancement

#53 Add logging and java assertions to FindCommand class
  logs/findCommandLogs.log
  src/main/java/seedu/commands/FindCommand.java
  src/test/java/seedu/commands/FindCommandTest.java
Labels: type.Enhancement

#54 Add assert and logging for HelpCommand and ExitCommand
  logs/findCommandLogs.log
  logs/findCommandLogs.log.1
  logs/findCommandLogs.log.2
  src/main/java/seedu/commands/ExitCommand.java
  src/main/java/seedu/commands/HelpCommand.java
Labels: type.Enhancement

#55 Update logic and code quality of ListCommand
  src/main/java/seedu/commands/ListCommand.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/ui/UI.java
  src/test/java/seedu/commands/HelpCommandTest.java
  src/test/java/seedu/commands/ListCommandTest.java
  src/test/java/seedu/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement

#66 Enable assertions in Gradle
  build.gradle
Labels: type.Enhancement

#71 Repurpose style, architecture.puml from Addressbook
  docs/DeveloperGuide.md
  docs/diagram/Architecture.puml
  docs/diagram/ListSequenceDiagram.puml
  docs/diagram/Style.puml
  docs/images/ArchitectureDiagram.png
  docs/images/ListSequenceDiagram.png
Labels: type.Task

#74 Update DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/diagram/AddSequenceDiagram.puml
  docs/diagram/Style.puml
  docs/images/AddSequenceDiagram.png
  src/main/java/seedu/commands/AddCommand.java
Labels: type.Task

#75 Update ListCommand and List Implementation of DG
  docs/DeveloperGuide.md
  docs/diagram/ListSequenceDiagram.puml
  docs/images/ListSequenceDiagram.png
  src/main/java/seedu/commands/ListCommand.java
  src/main/java/seedu/common/Messages.java
  src/main/java/seedu/data/Resource.java
  src/main/java/seedu/ui/UI.java
  src/test/java/seedu/commands/ListCommandTest.java
  src/test/java/seedu/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, type.Task

#76 Add more user stories as well as manual testing
  docs/DeveloperGuide.md
Labels: type.Enhancement

#77 Add find command details on DG
  docs/DeveloperGuide.md
Labels: priority.High, type.Task

#84 Add updates to UG
  docs/UserGuide.md
  src/main/java/seedu/ui/UI.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement

#86 Add EditCommand feature and update User Guide
  docs/UserGuide.md
  src/main/java/seedu/commands/EditCommand.java
  src/main/java/seedu/parser/Parser.java
  src/test/java/seedu/commands/EditCommandTest.java
  src/test/java/seedu/commands/ListCommandTest.java
  src/test/java/seedu/util/TestUtil.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task

#87 Add Status to resources
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/commands/AddCommand.java
  src/main/java/seedu/commands/EditCommand.java
  src/main/java/seedu/data/Book.java
  src/main/java/seedu/data/Resource.java
  src/main/java/seedu/data/Status.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/ui/UI.java
  src/test/java/seedu/commands/AddCommandTest.java
  src/test/java/seedu/commands/DeleteCommandTest.java
  src/test/java/seedu/commands/EditCommandTest.java
  src/test/java/seedu/commands/FindCommandTest.java
  src/test/java/seedu/commands/HelpCommandTest.java
  src/test/java/seedu/parser/ParserTest.java
  src/test/java/seedu/util/TestUtil.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Epic, type.Story, priority.High, type.Task

#94 Add event commands
  src/main/java/seedu/commands/Command.java
  src/main/java/seedu/commands/events/EventAddCommand.java
  src/main/java/seedu/commands/events/EventDeleteCommand.java
  src/main/java/seedu/commands/events/EventListCommand.java
  src/main/java/seedu/data/Event.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/ui/UI.java
  src/test/java/seedu/commands/HelpCommandTest.java
  src/test/java/seedu/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Story, type.Task

#99 Fix findCommand assertion issue
  src/main/java/seedu/commands/FindCommand.java
  src/test/java/seedu/commands/FindCommandTest.java
Labels: priority.High, type.Bug

#100 Fix logs and consistency
  src/main/java/seedu/commands/AddCommand.java
  src/main/java/seedu/commands/Command.java
  src/main/java/seedu/commands/DeleteCommand.java
  src/main/java/seedu/commands/EditCommand.java
  src/main/java/seedu/commands/ExitCommand.java
  src/main/java/seedu/commands/FindCommand.java
  src/main/java/seedu/commands/HelpCommand.java
  src/main/java/seedu/commands/ListCommand.java
  src/main/java/seedu/data/Resource.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/ui/UI.java
Labels: type.Enhancement, type.Bug

#98 Add Different Types of Resources
  docs/UserGuide.md
  src/main/java/seedu/commands/AddCommand.java
  src/main/java/seedu/data/Book.java
  src/main/java/seedu/data/CD.java
  src/main/java/seedu/data/CreateResource.java
  src/main/java/seedu/data/Magazine.java
  src/main/java/seedu/data/Newspaper.java
  src/main/java/seedu/data/Resource.java
  src/main/java/seedu/data/eBook.java
  src/main/java/seedu/data/eMagazine.java
  src/main/java/seedu/data/eNewspaper.java
  src/main/java/seedu/parser/Parser.java
  src/test/java/seedu/parser/ParserTest.java
  src/test/java/seedu/util/TestUtil.java
Labels: type.Epic, type.Story, priority.High
