Repository AY2324S1-CS2113T-W11-1/tp, pull requests merged in 2023-11, with the labels that each got.

#102 Add CommandResult class and feedbackToUser variable to all commands
  src/main/java/seedu/commands/AddCommand.java
  src/main/java/seedu/commands/Command.java
  src/main/java/seedu/commands/CommandResult.java
  src/main/java/seedu/commands/DeleteCommand.java
  src/main/java/seedu/commands/EditCommand.java
  src/main/java/seedu/commands/ExitCommand.java
  src/main/java/seedu/commands/FindCommand.java
  src/main/java/seedu/commands/HelpCommand.java
  src/main/java/seedu/commands/ListCommand.java
  src/main/java/seedu/commands/events/EventAddCommand.java
  src/main/java/seedu/commands/events/EventDeleteCommand.java
  src/main/java/seedu/commands/events/EventListCommand.java
  src/main/java/seedu/common/Messages.java
  src/main/java/seedu/parser/Parser.java
  src/test/java/seedu/commands/EditCommandTest.java
  src/test/java/seedu/commands/ListCommandTest.java
  src/test/java/seedu/util/TestUtil.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement

#104 Add sequence diagram for Find Command
  docs/DeveloperGuide.md
  docs/diagram/FindSequenceDiagram.puml
  docs/images/FindSequenceDiagram.png
Labels: priority.High, type.Task

#105 Add storage
  build.gradle
  src/main/java/seedu/commands/events/EventListCommand.java
  src/main/java/seedu/data/Event.java
  src/main/java/seedu/data/Resource.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/storage/Storage.java
  src/main/java/seedu/syslib/Syslib.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Story, priority.High

#108 Update find sequence diagram, add minor UI enhancement
  docs/diagram/FindSequenceDiagram.puml
  docs/images/FindSequenceDiagram.png
  storage.txt
Labels: type.Enhancement

#109 Update UserGuide.md
  docs/UserGuide.md
Labels: type.Task

#112 Update findcommand filtering and fix storage class bug
  logs/editCommandLogs.log
  logs/exitCommandLogs.log
  logs/exitCommandLogs.log.lck
  logs/findCommandLogs.log
  logs/findCommandLogs.log.lck
  logs/helpCommandLogs.log
  logs/helpCommandLogs.log.lck
  logs/listCommandLogs.log
  logs/listCommandLogs.log.lck
  src/main/java/seedu/commands/AddCommand.java
  src/main/java/seedu/commands/Command.java
  src/main/java/seedu/commands/DeleteCommand.java
  src/main/java/seedu/commands/EditCommand.java
  src/main/java/seedu/commands/FindCommand.java
  src/main/java/seedu/commands/ListCommand.java
  src/main/java/seedu/commands/events/EventAddCommand.java
  src/main/java/seedu/commands/events/EventDeleteCommand.java
  src/main/java/seedu/commands/events/EventListCommand.java
  src/main/java/seedu/data/CreateResource.java
  src/main/java/seedu/data/resources/Book.java
  src/main/java/seedu/data/resources/CD.java
  src/main/java/seedu/data/resources/EBook.java
  src/main/java/seedu/data/resources/EMagazine.java
  src/main/java/seedu/data/resources/ENewspaper.java
  src/main/java/seedu/data/resources/Magazine.java
  src/main/java/seedu/data/resources/Newspaper.java
  src/main/java/seedu/data/resources/Resource.java
  src/main/java/seedu/exception/SysLibException.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/storage/Storage.java
  src/main/java/seedu/syslib/Syslib.java
  src/main/java/seedu/ui/UI.java
  src/test/java/seedu/commands/AddCommandTest.java
  src/test/java/seedu/commands/DeleteCommandTest.java
  src/test/java/seedu/commands/EditCommandTest.java
  src/test/java/seedu/commands/FindCommandTest.java
  src/test/java/seedu/commands/ListCommandTest.java
  src/test/java/seedu/commands/events/EventAddCommandTest.java
  src/test/java/seedu/commands/events/EventDeleteCommandTest.java
  src/test/java/seedu/commands/events/EventListCommandTest.java
  src/test/java/seedu/parser/ParserTest.java
  src/test/java/seedu/util/TestUtil.java
  storage.txt
Labels: type.Enhancement, priority.High, type.Bug

#118 Add findcommandfilters
  .gitignore
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagram/FindSequenceDiagram.puml
  docs/images/FindSequenceDiagram.png
  logs/editCommandLogs.log
  logs/editCommandLogs.log.1
  logs/exitCommandLogs.log
  logs/exitCommandLogs.log.1
  logs/findCommandLogs.log
  logs/findCommandLogs.log.1
  logs/helpCommandLogs.log
  logs/helpCommandLogs.log.1
  logs/listCommandLogs.log
  logs/listCommandLogs.log.1
  src/main/java/seedu/commands/FindCommand.java
  src/test/java/seedu/commands/FindCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement

#133 Update Overall Architecture Diagram for Storage and Data component
  docs/DeveloperGuide.md
  docs/diagram/Architecture.puml
  docs/images/ArchitectureDiagram.png
Labels: type.Task

#134 Add Filter by Status for List Command and fix logging for List, Edit
  docs/UserGuide.md
  src/main/java/seedu/commands/EditCommand.java
  src/main/java/seedu/commands/ListCommand.java
  src/main/java/seedu/common/FormatMessages.java
  src/test/java/seedu/commands/EditCommandTest.java
  src/test/java/seedu/commands/ListCommandTest.java
Labels: type.Enhancement

#137 Update format of displaying resources
  logs/editCommandLogs.log
  src/main/java/seedu/commands/ListCommand.java
  src/main/java/seedu/common/FormatMessages.java
  src/main/java/seedu/data/resources/Book.java
  src/main/java/seedu/data/resources/CD.java
  src/main/java/seedu/data/resources/EBook.java
  src/main/java/seedu/data/resources/EMagazine.java
  src/main/java/seedu/data/resources/ENewspaper.java
  src/main/java/seedu/data/resources/Magazine.java
  src/main/java/seedu/data/resources/Newspaper.java
  src/main/java/seedu/data/resources/Resource.java
  src/main/java/seedu/ui/UI.java
  src/test/java/seedu/commands/ListCommandTest.java
  src/test/java/seedu/parser/ParserTest.java
  storage.txt
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement

#139 Update storage to load events as well
  .gitignore
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/storage/Storage.java
  src/main/java/seedu/syslib/Syslib.java
  storage.txt
Labels: priority.High, type.Task

#140 Improve showResources by adjusting for long attributes
  src/main/java/seedu/data/resources/Book.java
  src/main/java/seedu/data/resources/CD.java
  src/main/java/seedu/data/resources/EBook.java
  src/main/java/seedu/data/resources/EMagazine.java
  src/main/java/seedu/data/resources/ENewspaper.java
  src/main/java/seedu/data/resources/Magazine.java
  src/main/java/seedu/data/resources/Newspaper.java
  src/main/java/seedu/data/resources/Resource.java
  src/main/java/seedu/ui/UI.java
  src/test/java/seedu/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement

#143 Update editCommand to support different types of resources
  src/main/java/seedu/commands/EditCommand.java
  src/main/java/seedu/data/resources/Book.java
  src/test/java/seedu/commands/EditCommandTest.java
  src/test/java/seedu/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement

#148 Update Introductory, List, and Edit section for User Guide
  docs/UserGuide.md
  docs/images/SysLib Logo.png
Labels: type.Enhancement

#151 000verflow create resourcelist and eventlist
  logs/editCommandLogs.log
  logs/editCommandLogs.log.1
  logs/exitCommandLogs.log
  logs/findCommandLogs.log
  logs/helpCommandLogs.log
  src/main/java/seedu/commands/AddCommand.java
  src/main/java/seedu/commands/Command.java
  src/main/java/seedu/commands/DeleteCommand.java
  src/main/java/seedu/commands/EditCommand.java
  src/main/java/seedu/commands/ExitCommand.java
  src/main/java/seedu/commands/FindCommand.java
  src/main/java/seedu/commands/HelpCommand.java
  src/main/java/seedu/commands/ListCommand.java
  src/main/java/seedu/commands/events/EventAddCommand.java
  src/main/java/seedu/commands/events/EventDeleteCommand.java
  src/main/java/seedu/commands/events/EventListCommand.java
  src/main/java/seedu/data/GenericList.java
  src/main/java/seedu/data/events/Event.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/storage/Storage.java
  src/main/java/seedu/syslib/Syslib.java
  src/main/java/seedu/ui/UI.java
  src/test/java/seedu/commands/AddCommandTest.java
  src/test/java/seedu/commands/DeleteCommandTest.java
  src/test/java/seedu/commands/EditCommandTest.java
  src/test/java/seedu/commands/ExitCommandTest.java
  src/test/java/seedu/commands/FindCommandTest.java
  src/test/java/seedu/commands/HelpCommandTest.java
  src/test/java/seedu/commands/ListCommandTest.java
  src/test/java/seedu/commands/events/EventAddCommandTest.java
  src/test/java/seedu/commands/events/EventDeleteCommandTest.java
  src/test/java/seedu/commands/events/EventListCommandTest.java
  src/test/java/seedu/parser/ParserTest.java
  src/test/java/seedu/util/TestUtil.java
Labels: type.Enhancement, priority.High

#152 Update storageid handling
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/commands/FindCommand.java
  src/main/java/seedu/storage/Storage.java
  src/main/java/seedu/syslib/Syslib.java
  src/main/java/seedu/ui/UI.java
  src/test/java/seedu/commands/AddCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, priority.High, type.Bug

#153 Update EditCommand to use ID instead of ISBN
  src/main/java/seedu/commands/EditCommand.java
  src/main/java/seedu/commands/ListCommand.java
  src/main/java/seedu/ui/MessageFormatter.java
  src/main/java/seedu/ui/ResourceDisplayFormatter.java
  src/main/java/seedu/ui/UI.java
  src/test/java/seedu/commands/EditCommandTest.java
  src/test/java/seedu/parser/ParserTest.java
  src/test/java/seedu/util/TestUtil.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Enhancement

#154 Add Summary
  .gitignore
  src/main/java/seedu/commands/DeleteCommand.java
  src/main/java/seedu/commands/SummaryCommand.java
  src/main/java/seedu/commands/events/EventAddCommand.java
  src/main/java/seedu/commands/events/EventDeleteCommand.java
  src/main/java/seedu/commands/events/EventListCommand.java
  src/main/java/seedu/parser/Parser.java
  src/test/java/seedu/commands/DeleteCommandTest.java
  src/test/java/seedu/commands/SummaryCommandTest.java
  src/test/java/seedu/parser/ParserTest.java
  storage.txt
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
  text-ui-test/storage.txt
Labels: type.Enhancement, priority.Medium

#156 EventEdit UpdateUG
  docs/UserGuide.md
  src/main/java/seedu/commands/Command.java
  src/main/java/seedu/commands/DeleteCommand.java
  src/main/java/seedu/commands/SummaryCommand.java
  src/main/java/seedu/commands/events/EventEditCommand.java
  src/main/java/seedu/commands/events/EventListCommand.java
  src/test/java/seedu/commands/events/EventEditCommandTest.java
  src/test/java/seedu/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, priority.Medium

#159 Update first draft of PPP
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/YingXia.md
  docs/team/yingx9.md
  src/main/java/seedu/commands/EditCommand.java
  src/main/java/seedu/commands/ListCommand.java
  src/test/java/seedu/commands/EditCommandTest.java
  src/test/java/seedu/commands/ListCommandTest.java
  src/test/java/seedu/util/TestUtil.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task

#160 Add PPP
  docs/team/BenjaminNg.md
  docs/team/bnjm2000.md
Labels: type.Task

#166 Update storagefile
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagram/FindSequenceDiagram.puml
  docs/diagram/Storage.puml
  docs/images/FindSequenceDiagram.png
  docs/images/StorageDiagram.png
  docs/team/000verflow.md
  docs/team/ashokbalaji.md
  logs/editCommandLogs.log
  logs/editCommandLogs.log.1
  logs/exitCommandLogs.log
  logs/findCommandLogs.log
  logs/helpCommandLogs.log
  src/main/java/seedu/commands/FindCommand.java
  src/main/java/seedu/storage/Storage.java
  src/main/java/seedu/syslib/Syslib.java
  src/main/java/seedu/ui/UI.java
  src/test/java/seedu/commands/ExitCommandTest.java
  src/test/java/seedu/parser/ParserTest.java
  storage.txt
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, type.Task, type.Bug

#171 Fix Event Edit
  src/main/java/seedu/commands/events/EventAddCommand.java
  src/main/java/seedu/commands/events/EventEditCommand.java
  src/test/java/seedu/commands/events/EventEditCommandTest.java
Labels: type.Bug

#172 Update Developer's Guide
  docs/DeveloperGuide.md
  docs/diagram/EditActivityDiagram.puml
  docs/diagram/ListSequenceDiagram.puml
  docs/diagram/ShowResourcesSequenceDiagram.puml
  docs/images/EditActivityDiagram.png
  docs/images/ListSequenceDiagram.png
  docs/images/ShowResourcesSequenceDiagram.png
  src/main/java/seedu/commands/ListCommand.java
Labels: type.Task

#173 Update User Guide
  docs/UserGuide.md
  src/main/java/seedu/parser/resources/ParseCD.java
  src/main/java/seedu/parser/resources/ParseMagazine.java
  src/main/java/seedu/parser/resources/ParseNewspaper.java
Labels: type.Task

#174 Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagram/AddSequenceDiagram.puml
  docs/diagram/Style.puml
  docs/images/AddSequenceDiagram.png
  src/main/java/seedu/commands/AddCommand.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task

#175 Check Code Quality and Coding Standards
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/commands/AddCommand.java
  src/main/java/seedu/data/CreateResource.java
  src/main/java/seedu/data/resources/Book.java
  src/main/java/seedu/data/resources/CD.java
  src/main/java/seedu/data/resources/EBook.java
  src/main/java/seedu/data/resources/Resource.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/parser/resources/ParseBook.java
  src/main/java/seedu/parser/resources/ParseCD.java
  src/main/java/seedu/parser/resources/ParseEBook.java
  src/main/java/seedu/parser/resources/ParseEMagazine.java
  src/main/java/seedu/parser/resources/ParseENewspaper.java
  src/main/java/seedu/parser/resources/ParseMagazine.java
  src/main/java/seedu/parser/resources/ParseNewspaper.java
  src/main/java/seedu/parser/resources/ParseResource.java
  src/main/java/seedu/ui/MessageFormatter.java
  src/main/java/seedu/ui/Messages.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Task

#178 Update misc
  META-INF/MANIFEST.MF
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/commands/FindCommand.java
  src/main/java/seedu/storage/Storage.java
  src/main/java/seedu/syslib/Syslib.java
  src/main/java/seedu/ui/UI.java
  src/test/java/seedu/commands/HelpCommandTest.java
  src/test/java/seedu/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, type.Bug

#176 Add Messages class specific to EditCommand and ListCommand
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/images/List Screenshots/fontsize.png
  docs/images/List Screenshots/listimage.png
  docs/images/List Screenshots/listproblemimg.png
  docs/images/List Screenshots/resizeicon.png
  docs/images/List Screenshots/terminalimg.png
  docs/team/yingx9.md
  src/main/java/seedu/commands/EditCommand.java
  src/main/java/seedu/commands/ListCommand.java
  src/main/java/seedu/data/resources/Book.java
  src/main/java/seedu/data/resources/CD.java
  src/main/java/seedu/data/resources/EBook.java
  src/main/java/seedu/data/resources/EMagazine.java
  src/main/java/seedu/data/resources/ENewspaper.java
  src/main/java/seedu/data/resources/Magazine.java
  src/main/java/seedu/data/resources/Newspaper.java
  src/main/java/seedu/data/resources/Resource.java
  src/main/java/seedu/ui/EditCommandMessages.java
  src/main/java/seedu/ui/ListCommandMessages.java
  src/main/java/seedu/ui/ResourceDisplayFormatter.java
  src/main/java/seedu/ui/UI.java
  src/test/java/seedu/commands/EditCommandTest.java
  src/test/java/seedu/commands/HelpCommandTest.java
  src/test/java/seedu/commands/ListCommandTest.java
  src/test/java/seedu/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement

#184 Add dg updates
  data/storage.txt
  docs/DeveloperGuide.md
  docs/diagram/Storage.puml
  docs/images/StorageDeleteResource.png
  docs/images/StorageDiagram.png
  docs/images/StorageEditResource.png
  docs/images/StorageNewResources.png
  docs/team/000verflow.md
  src/main/java/seedu/commands/FindCommand.java
  src/main/java/seedu/storage/Storage.java
  src/main/java/seedu/syslib/Syslib.java
  src/main/java/seedu/ui/FindCommandMessages.java
  storage.txt
  text-ui-test/EXPECTED.TXT
  text-ui-test/storage.txt
Labels: type.Enhancement, priority.High

#182 Fix logs, EventList and ResourceList
  src/main/java/seedu/commands/AddCommand.java
  src/main/java/seedu/commands/DeleteCommand.java
  src/main/java/seedu/commands/EditCommand.java
  src/main/java/seedu/commands/ExitCommand.java
  src/main/java/seedu/commands/FindCommand.java
  src/main/java/seedu/commands/HelpCommand.java
  src/main/java/seedu/commands/ListCommand.java
  src/main/java/seedu/commands/SummaryCommand.java
  src/main/java/seedu/commands/events/EventAddCommand.java
  src/main/java/seedu/commands/events/EventDeleteCommand.java
  src/main/java/seedu/commands/events/EventEditCommand.java
  src/main/java/seedu/commands/events/EventListCommand.java
  src/main/java/seedu/data/GenericList.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/storage/Storage.java
  src/test/java/seedu/commands/AddCommandTest.java
  src/test/java/seedu/commands/DeleteCommandTest.java
  src/test/java/seedu/commands/FindCommandTest.java
  src/test/java/seedu/commands/events/EventAddCommandTest.java
  src/test/java/seedu/commands/events/EventEditCommandTest.java
Labels: type.Bug

#183 Add Component Diagram to Developer's Guide and update explanations
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagram/Architecture.puml
  docs/diagram/ComponentDiagram.puml
  docs/images/ArchitectureDiagram.png
  docs/images/ComponentDiagram.png
  docs/images/List Screenshots/resizeicon.png
  docs/team/yingx9.md
Labels: type.Task

#186 Update dg diagram
  docs/DeveloperGuide.md
  docs/diagram/Storage.puml
  docs/images/StorageDiagram.png
Labels: type.Enhancement

#187 Fix Consistency
  data/storage.txt
  src/main/java/seedu/commands/AddCommand.java
  src/main/java/seedu/commands/Command.java
  src/main/java/seedu/commands/DeleteCommand.java
  src/main/java/seedu/commands/EditCommand.java
  src/main/java/seedu/commands/ExitCommand.java
  src/main/java/seedu/commands/FindCommand.java
  src/main/java/seedu/commands/ListCommand.java
  src/main/java/seedu/commands/events/EventAddCommand.java
  src/main/java/seedu/commands/events/EventDeleteCommand.java
  src/main/java/seedu/commands/events/EventEditCommand.java
  src/main/java/seedu/commands/events/EventListCommand.java
  src/main/java/seedu/data/GenericList.java
  src/main/java/seedu/data/resources/Book.java
  src/main/java/seedu/data/resources/CD.java
  src/main/java/seedu/data/resources/EMagazine.java
  src/main/java/seedu/data/resources/ENewspaper.java
  src/main/java/seedu/data/resources/Magazine.java
  src/main/java/seedu/data/resources/Newspaper.java
  src/main/java/seedu/data/resources/Resource.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/parser/SuggestParser.java
  src/main/java/seedu/storage/Storage.java
  src/main/java/seedu/syslib/Syslib.java
  src/main/java/seedu/ui/MessageFormatter.java
  src/main/java/seedu/ui/ResourceDisplayFormatter.java
  src/main/java/seedu/ui/UI.java
  src/test/java/seedu/commands/EditCommandTest.java
  src/test/java/seedu/commands/ExitCommandTest.java
  src/test/java/seedu/commands/HelpCommandTest.java
  src/test/java/seedu/commands/ListCommandTest.java
  src/test/java/seedu/commands/events/EventAddCommandTest.java
  src/test/java/seedu/commands/events/EventDeleteCommandTest.java
  src/test/java/seedu/commands/events/EventEditCommandTest.java
  src/test/java/seedu/commands/events/EventListCommandTest.java
  src/test/java/seedu/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, type.Bug

#180 Update PPP
  docs/team/bnjm2000.md
Labels: type.Enhancement

#188 Update UG & DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagram/EventEdit.puml
  docs/diagram/Style.puml
  docs/diagram/SummarySequenceDiagram.puml
  docs/images/EventEditDiagram.png
  docs/images/SummaryDiagram.png
  src/main/java/seedu/commands/SummaryCommand.java
  src/main/java/seedu/ui/UI.java
  src/test/java/seedu/commands/ExitCommandTest.java
  src/test/java/seedu/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement

#189 Fix bugs in UG, update Target Users and PPP
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/yingx9.md
  src/main/java/seedu/data/GenericList.java
  src/main/java/seedu/syslib/Syslib.java
  src/test/java/seedu/commands/EditCommandTest.java
  src/test/java/seedu/commands/ListCommandTest.java
  src/test/java/seedu/util/TestUtil.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement

#190 Fix DG formatting bug and update PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/000verflow.md
  docs/team/DavinciDelta.md
  docs/team/bnjm2000.md
  docs/team/joannejo.md
  docs/team/yingx9.md
  src/main/java/seedu/commands/ListCommand.java
  src/main/java/seedu/data/resources/Resource.java
  src/test/java/seedu/commands/ListCommandTest.java
Labels: type.Enhancement

#194 Update PPP and DG
  docs/DeveloperGuide.md
  docs/team/bnjm2000.md
Labels: type.Enhancement

#195 Update dg and storage
  data/storage.txt
  docs/DeveloperGuide.md
  docs/diagram/FindSequenceDiagram.puml
  docs/images/FindSequenceDiagram.png
  src/main/java/seedu/storage/Storage.java
  src/main/java/seedu/syslib/Syslib.java
  src/main/java/seedu/ui/UI.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, type.Bug

#192 Add Tests, rename ResourceList and EventList
  src/main/java/seedu/commands/Command.java
  src/main/java/seedu/commands/DeleteCommand.java
  src/main/java/seedu/commands/SummaryCommand.java
  src/main/java/seedu/commands/events/EventDeleteCommand.java
  src/main/java/seedu/commands/events/EventEditCommand.java
  src/main/java/seedu/data/GenericList.java
  src/main/java/seedu/syslib/Syslib.java
  src/test/java/seedu/commands/DeleteCommandTest.java
  src/test/java/seedu/commands/EditCommandTest.java
  src/test/java/seedu/commands/ListCommandTest.java
  src/test/java/seedu/commands/SummaryCommandTest.java
  src/test/java/seedu/commands/events/EventAddCommandTest.java
  src/test/java/seedu/commands/events/EventDeleteCommandTest.java
  src/test/java/seedu/commands/events/EventEditCommandTest.java
  src/test/java/seedu/util/TestUtil.java
Labels: type.Enhancement, type.Bug

#198 Update display message
  src/main/java/seedu/ui/EditCommandMessages.java
Labels: type.Enhancement

#199 Update PPP, DG and Fix bar for Summary
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/bnjm2000.md
  src/main/java/seedu/commands/SummaryCommand.java
  src/test/java/seedu/commands/SummaryCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, type.Bug

#203 Update readme.md
  README.md
Labels: type.Enhancement

#205 Fix Invalid First Word Bug for Add Command
  src/main/java/seedu/commands/AddCommand.java
  src/main/java/seedu/parser/Parser.java
  src/main/java/seedu/parser/resources/ParseBook.java
  src/main/java/seedu/ui/Messages.java
Labels: type.Bug

#206 Update UG Screenshot
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/List Screenshots/listexampleoutput.png
Labels: type.Enhancement

#214 Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagram/AddActivityDiagram.puml
  docs/diagram/AddSequenceDiagram.puml
  docs/images/AddActivityDiagram.png
  docs/images/AddSequenceDiagram.png
Labels: type.Task

#213 Fix EventDelete
  src/main/java/seedu/commands/events/EventDeleteCommand.java
  src/test/java/seedu/commands/events/EventDeleteCommandTest.java
Labels: type.Bug

#215 Update Project Portfolio Page
  docs/DeveloperGuide.md
  docs/team/joannejo.md
Labels: type.Task

#218 Update DG usecase and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/findcommandoutput.png
Labels: type.Enhancement

#219 Fix logo link
  README.md
Labels: type.Enhancement

#221 Update Project Portfolio Page
  docs/team/joannejo.md
Labels: type.Task

#222 Add Syslib version printout
  src/main/java/seedu/ui/UI.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement
